# Generated by Django 6.0.6 on 2026-06-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
