# Generated by Django 6.0.6 on 2026-06-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutinfo_email_aboutinfo_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
