# Generated by Django 6.0.6 on 2026-07-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aboutinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main', models.CharField(max_length=50)),
                ('catalog', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('custom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='footer_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='footer_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='footer_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='footer_work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='headline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='headline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
