# Generated by Django 6.0.6 on 2026-06-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_battlereview_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildproduct',
            name='stock_change',
            field=models.IntegerField(blank=True, help_text='Enter a positive number to add, or a negative number to subtract from current stock.', null=True, verbose_name='Add/Remove Stock (e.g. +142 or -5)'),
        ),
    ]
