# Generated by Django 6.0.6 on 2026-06-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_guildproduct_stock_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/', verbose_name='Product Image'),
        ),
    ]
