# Generated by Django 6.0.6 on 2026-06-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_guildproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildproduct',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
