# Generated by Django 6.0.6 on 2026-07-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_guildproduct_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
