# Generated by Django 6.0.6 on 2026-06-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyorder',
            options={'ordering': ['-id']},
        ),
    ]
