# Generated by Django 6.0.6 on 2026-06-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_supplyorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
