# Generated by Django 6.0.6 on 2026-06-19 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShieldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lord_name', models.CharField(max_length=50)),
                ('shield_type', models.CharField(choices=[('SHIELD', 'A knight shield with its coat of arms'), ('SADDLE', 'Customizing a horse saddle'), ('ENGRAVING', 'Engraving on the blade of a sword')], default='SHIELD', max_length=20)),
                ('heraldry_description', models.TextField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting the blacksmith to start'), ('IN_PROGRESS', 'The craftsmen are making'), ('READY', 'Ready to ship')], default='WAITING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
